namespace TTNOverlay.Services;

internal static partial class ZhStrings
{
    private static readonly Dictionary<string, string> ModerationPanelEntries = new()
    {
        ["MainWindow_MuteMenu"] = "🔇 禁言",
        ["MainWindow_WarnMenu"] = "⚠ 警告",
        ["MainWindow_BanMenu"] = "⛔ 封禁",
        ["MainWindow_SettingsTooltip"] = "设置",
        ["MainWindow_ToggleBordersTooltip"] = "显示/隐藏边框",
        ["MainWindow_RefreshWithIcon"] = "🔄 刷新",
        ["MainWindow_LogoutWithIcon"] = "🚪 登出",
        ["MainWindow_MuteDurationHeader"] = "禁言时长",
        ["MainWindow_1Minute"] = "1 分钟",
        ["MainWindow_5Minutes"] = "5 分钟",
        ["MainWindow_10Minutes"] = "10 分钟",
        ["MainWindow_30Minutes"] = "30 分钟",
        ["MainWindow_1Hour"] = "1 小时",
        ["MainWindow_24Hours"] = "24 小时",
        ["MainWindow_3Days"] = "3 天",
        ["MainWindow_7Days"] = "7 天",
        ["MainWindow_14Days"] = "14 天",
        ["MainWindow_1Day"] = "1 天",
        ["MainWindow_1Week"] = "1 周",
        ["MainWindow_1Month"] = "1 个月",
        ["MainWindow_3Seconds"] = "3 秒",
        ["MainWindow_5Seconds"] = "5 秒",
        ["MainWindow_10Seconds"] = "10 秒",
        ["MainWindow_30Seconds"] = "30 秒",
        ["MainWindow_60Seconds"] = "60 秒",
        ["MainWindow_120Seconds"] = "120 秒",
        ["MainWindow_Custom"] = "自定义……",
        ["MainWindow_CustomHoursTooltip"] = "小时数（最大 336 = 14 天）",
        ["MainWindow_HoursUnit"] = "小时",
        ["MainWindow_DaysUnit"] = "天",
        ["MainWindow_SubscribersOnly"] = "仅订阅者",
        ["MainWindow_EmotesOnly"] = "仅表情",
        ["MainWindow_UniqueChat"] = "唯一聊天（禁止重复消息）",
        ["MainWindow_FollowersOnly"] = "仅关注者（最短关注时长）",
        ["MainWindow_FollowersOnlyTooltip"] = "只有关注该频道至少这么多分钟的观众才能发言",
        ["MainWindow_SlowMode"] = "慢速模式（消息间隔秒数）",
        ["MainWindow_SlowModeTooltip"] = "每个用户发送一条消息后必须等待这么多秒才能发下一条",
        ["MainWindow_SaveChatSettings"] = "保存聊天设置",
        ["MainWindow_RefreshChatSettingsTooltip"] = "刷新设置",
        ["MainWindow_ChatSettingsHeader"] = "聊天设置",
        ["MainWindow_ConnectedChatters"] = "已连接的观众",
        ["MainWindow_UnbanUserHeader"] = "解除封禁用户",
        ["MainWindow_Unban"] = "解除封禁",
        ["MainWindow_ActiveSanctions"] = "现行惩戒",
        ["MainWindow_RefreshSanctionsTooltip"] = "刷新惩戒列表",
    };
}