namespace TTNOverlay.Services;

internal static partial class JaStrings
{
    private static readonly Dictionary<string, string> ModerationPanelEntries = new()
    {
        ["MainWindow_MuteMenu"] = "🔇 ミュート",
        ["MainWindow_WarnMenu"] = "⚠ 警告",
        ["MainWindow_BanMenu"] = "⛔ BAN",
        ["MainWindow_SettingsTooltip"] = "設定",
        ["MainWindow_ToggleBordersTooltip"] = "枠線の表示/非表示",
        ["MainWindow_RefreshWithIcon"] = "🔄 更新",
        ["MainWindow_LogoutWithIcon"] = "🚪 ログアウト",
        ["MainWindow_MuteDurationHeader"] = "ミュート時間",
        ["MainWindow_1Minute"] = "1分",
        ["MainWindow_5Minutes"] = "5分",
        ["MainWindow_10Minutes"] = "10分",
        ["MainWindow_30Minutes"] = "30分",
        ["MainWindow_1Hour"] = "1時間",
        ["MainWindow_24Hours"] = "24時間",
        ["MainWindow_3Days"] = "3日",
        ["MainWindow_7Days"] = "7日",
        ["MainWindow_14Days"] = "14日",
        ["MainWindow_1Day"] = "1日",
        ["MainWindow_1Week"] = "1週間",
        ["MainWindow_1Month"] = "1ヶ月",
        ["MainWindow_3Seconds"] = "3秒",
        ["MainWindow_5Seconds"] = "5秒",
        ["MainWindow_10Seconds"] = "10秒",
        ["MainWindow_30Seconds"] = "30秒",
        ["MainWindow_60Seconds"] = "60秒",
        ["MainWindow_120Seconds"] = "120秒",
        ["MainWindow_Custom"] = "カスタム...",
        ["MainWindow_CustomHoursTooltip"] = "時間 (最大336 = 14日)",
        ["MainWindow_HoursUnit"] = "時間",
        ["MainWindow_DaysUnit"] = "日",
        ["MainWindow_SubscribersOnly"] = "サブスクリプションのみ",
        ["MainWindow_EmotesOnly"] = "絵文字のみ",
        ["MainWindow_UniqueChat"] = "ユニークチャット (メッセージの重複禁止)",
        ["MainWindow_FollowersOnly"] = "フォロワーのみ (経過時間)",
        ["MainWindow_FollowersOnlyTooltip"] = "チャンネルをフォローしてから指定された分数以上経過した視聴者のみがチャットできます",
        ["MainWindow_SlowMode"] = "スローモード (メッセージ間隔・秒)",
        ["MainWindow_SlowModeTooltip"] = "各ユーザーは次のメッセージを送信するまでにこの秒数を待つ必要があります",
        ["MainWindow_SaveChatSettings"] = "チャット設定を保存",
        ["MainWindow_RefreshChatSettingsTooltip"] = "設定を更新",
        ["MainWindow_ChatSettingsHeader"] = "チャット設定",
        ["MainWindow_ConnectedChatters"] = "接続中の視聴者",
        ["MainWindow_UnbanUserHeader"] = "BAN解除ユーザー",
        ["MainWindow_Unban"] = "BAN解除",
        ["MainWindow_ActiveSanctions"] = "アクティブな制裁",
        ["MainWindow_RefreshSanctionsTooltip"] = "制裁を更新",
    };
}