<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <Version>1.2.2</Version>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Resources\icon.ico</ApplicationIcon>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AssemblyName>TTNOverlay</AssemblyName>
    <AssemblyTitle>TTNOverlay</AssemblyTitle>
    <Product>TTNOverlay</Product>
    <FileDescription>TTNOverlay</FileDescription>
    <RootNamespace>TTNOverlay</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Webp-Wrapper-for-NET-Win-x64" Version="1.6.0" />
    <PackageReference Include="Vortice.Direct2D1" Version="3.8.3" />
    <PackageReference Include="Vortice.Mathematics" Version="2.1.1" />
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="TTNOverlay.Tests\**" />
    <EmbeddedResource Remove="TTNOverlay.Tests\**" />
    <None Remove="TTNOverlay.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\icon.ico" />
    <EmbeddedResource Include="Resources\twitch_white.ico" />
    <EmbeddedResource Include="Resources\twitch_dark.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="app.manifest" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Sounds\*.wav">
      <Link>Sounds\%(Filename)%(Extension)</Link>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>TTNOverlay.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>