namespace TTNOverlay.Services;

internal static partial class PtStrings
{
    private static readonly Dictionary<string, string> ModerationPanelEntries = new()
    {
        ["MainWindow_MuteMenu"] = "🔇 Mutear",
        ["MainWindow_WarnMenu"] = "⚠ Advertir",
        ["MainWindow_BanMenu"] = "⛔ Banir",
        ["MainWindow_SettingsTooltip"] = "Configurações",
        ["MainWindow_ToggleBordersTooltip"] = "Ocultar/mostrar bordas",
        ["MainWindow_RefreshWithIcon"] = "🔄 Atualizar",
        ["MainWindow_LogoutWithIcon"] = "🚪 Sair",
        ["MainWindow_MuteDurationHeader"] = "DURAÇÃO DO MUTE",
        ["MainWindow_1Minute"] = "1 minuto",
        ["MainWindow_5Minutes"] = "5 minutos",
        ["MainWindow_10Minutes"] = "10 minutos",
        ["MainWindow_30Minutes"] = "30 minutos",
        ["MainWindow_1Hour"] = "1 hora",
        ["MainWindow_24Hours"] = "24 horas",
        ["MainWindow_3Days"] = "3 dias",
        ["MainWindow_7Days"] = "7 dias",
        ["MainWindow_14Days"] = "14 dias",
        ["MainWindow_1Day"] = "1 dia",
        ["MainWindow_1Week"] = "1 semana",
        ["MainWindow_1Month"] = "1 mês",
        ["MainWindow_3Seconds"] = "3 segundos",
        ["MainWindow_5Seconds"] = "5 segundos",
        ["MainWindow_10Seconds"] = "10 segundos",
        ["MainWindow_30Seconds"] = "30 segundos",
        ["MainWindow_60Seconds"] = "60 segundos",
        ["MainWindow_120Seconds"] = "120 segundos",
        ["MainWindow_Custom"] = "Personalizado...",
        ["MainWindow_CustomHoursTooltip"] = "Horas (máx. 336 = 14 dias)",
        ["MainWindow_HoursUnit"] = "horas",
        ["MainWindow_DaysUnit"] = "dias",
        ["MainWindow_SubscribersOnly"] = "Apenas inscritos",
        ["MainWindow_EmotesOnly"] = "Apenas emotes",
        ["MainWindow_UniqueChat"] = "Chat único (sem mensagens repetidas)",
        ["MainWindow_FollowersOnly"] = "Apenas seguidores (min. de antiguidade)",
        ["MainWindow_FollowersOnlyTooltip"] = "Apenas podem conversar quem segue o canal há pelo menos essa quantidade de minutos",
        ["MainWindow_SlowMode"] = "Modo lento (seg. entre mensagens)",
        ["MainWindow_SlowModeTooltip"] = "Cada usuário deve esperar essa quantidade de segundos entre uma mensagem e a seguinte",
        ["MainWindow_SaveChatSettings"] = "Salvar configurações do chat",
        ["MainWindow_RefreshChatSettingsTooltip"] = "Atualizar configurações",
        ["MainWindow_ChatSettingsHeader"] = "CONFIGURAÇÕES DO CHAT",
        ["MainWindow_ConnectedChatters"] = "USUÁRIOS CONECTADOS",
        ["MainWindow_UnbanUserHeader"] = "DESBANIR USUÁRIO",
        ["MainWindow_Unban"] = "Desbanir",
        ["MainWindow_ActiveSanctions"] = "SANCIONADOS ATIVOS",
        ["MainWindow_RefreshSanctionsTooltip"] = "Atualizar sancionados",
    };
}