namespace TTNOverlay.Services;

internal static partial class FrStrings
{
    private static readonly Dictionary<string, string> ModerationPanelEntries = new()
    {
        ["MainWindow_MuteMenu"] = "🔇 Muet",
        ["MainWindow_WarnMenu"] = "⚠ Avertir",
        ["MainWindow_BanMenu"] = "⛔ Bannir",
        ["MainWindow_SettingsTooltip"] = "Paramètres",
        ["MainWindow_ToggleBordersTooltip"] = "Afficher/masquer les bordures",
        ["MainWindow_RefreshWithIcon"] = "🔄 Actualiser",
        ["MainWindow_LogoutWithIcon"] = "🚪 Se déconnecter",
        ["MainWindow_MuteDurationHeader"] = "DURÉE DU MUET",
        ["MainWindow_1Minute"] = "1 minute",
        ["MainWindow_5Minutes"] = "5 minutes",
        ["MainWindow_10Minutes"] = "10 minutes",
        ["MainWindow_30Minutes"] = "30 minutes",
        ["MainWindow_1Hour"] = "1 heure",
        ["MainWindow_24Hours"] = "24 heures",
        ["MainWindow_3Days"] = "3 jours",
        ["MainWindow_7Days"] = "7 jours",
        ["MainWindow_14Days"] = "14 jours",
        ["MainWindow_1Day"] = "1 jour",
        ["MainWindow_1Week"] = "1 semaine",
        ["MainWindow_1Month"] = "1 mois",
        ["MainWindow_3Seconds"] = "3 secondes",
        ["MainWindow_5Seconds"] = "5 secondes",
        ["MainWindow_10Seconds"] = "10 secondes",
        ["MainWindow_30Seconds"] = "30 secondes",
        ["MainWindow_60Seconds"] = "60 secondes",
        ["MainWindow_120Seconds"] = "120 secondes",
        ["MainWindow_Custom"] = "Personnalisé...",
        ["MainWindow_CustomHoursTooltip"] = "Heures (max. 336 = 14 jours)",
        ["MainWindow_HoursUnit"] = "heures",
        ["MainWindow_DaysUnit"] = "jours",
        ["MainWindow_SubscribersOnly"] = "Abonnés uniquement",
        ["MainWindow_EmotesOnly"] = "Émoticônes uniquement",
        ["MainWindow_UniqueChat"] = "Chat unique (pas de messages répétés)",
        ["MainWindow_FollowersOnly"] = "Abonnés uniquement (âge min.)",
        ["MainWindow_FollowersOnlyTooltip"] = "Seuls les spectateurs qui suivent la chaîne depuis au moins ce nombre de minutes peuvent discuter",
        ["MainWindow_SlowMode"] = "Mode lent (secondes entre les messages)",
        ["MainWindow_SlowModeTooltip"] = "Chaque utilisateur doit attendre ce nombre de secondes entre deux messages",
        ["MainWindow_SaveChatSettings"] = "Enregistrer les paramètres du chat",
        ["MainWindow_RefreshChatSettingsTooltip"] = "Actualiser les paramètres",
        ["MainWindow_ChatSettingsHeader"] = "PARAMÈTRES DU CHAT",
        ["MainWindow_ConnectedChatters"] = "PARTICIPANTS CONNECTÉS",
        ["MainWindow_UnbanUserHeader"] = "DÉBANNIR UN UTILISATEUR",
        ["MainWindow_Unban"] = "Débannir",
        ["MainWindow_ActiveSanctions"] = "SANCTIONS ACTIVES",
        ["MainWindow_RefreshSanctionsTooltip"] = "Actualiser les sanctions",
    };
}