namespace TTNOverlay.Services;

internal static partial class DeStrings
{
    private static readonly Dictionary<string, string> ModerationPanelEntries = new()
    {
        ["MainWindow_MuteMenu"] = "🔇 Stummschalten",
        ["MainWindow_WarnMenu"] = "⚠ Verwarnen",
        ["MainWindow_BanMenu"] = "⛔ Sperren",
        ["MainWindow_SettingsTooltip"] = "Einstellungen",
        ["MainWindow_ToggleBordersTooltip"] = "Rahmen ein-/ausblenden",
        ["MainWindow_RefreshWithIcon"] = "🔄 Aktualisieren",
        ["MainWindow_LogoutWithIcon"] = "🚪 Abmelden",
        ["MainWindow_MuteDurationHeader"] = "STUMMSCHALTDAUER",
        ["MainWindow_1Minute"] = "1 Minute",
        ["MainWindow_5Minutes"] = "5 Minuten",
        ["MainWindow_10Minutes"] = "10 Minuten",
        ["MainWindow_30Minutes"] = "30 Minuten",
        ["MainWindow_1Hour"] = "1 Stunde",
        ["MainWindow_24Hours"] = "24 Stunden",
        ["MainWindow_3Days"] = "3 Tage",
        ["MainWindow_7Days"] = "7 Tage",
        ["MainWindow_14Days"] = "14 Tage",
        ["MainWindow_1Day"] = "1 Tag",
        ["MainWindow_1Week"] = "1 Woche",
        ["MainWindow_1Month"] = "1 Monat",
        ["MainWindow_3Seconds"] = "3 Sekunden",
        ["MainWindow_5Seconds"] = "5 Sekunden",
        ["MainWindow_10Seconds"] = "10 Sekunden",
        ["MainWindow_30Seconds"] = "30 Sekunden",
        ["MainWindow_60Seconds"] = "60 Sekunden",
        ["MainWindow_120Seconds"] = "120 Sekunden",
        ["MainWindow_Custom"] = "Benutzerdefiniert...",
        ["MainWindow_CustomHoursTooltip"] = "Stunden (max. 336 = 14 Tage)",
        ["MainWindow_HoursUnit"] = "Stunden",
        ["MainWindow_DaysUnit"] = "Tage",
        ["MainWindow_SubscribersOnly"] = "Nur Abonnenten",
        ["MainWindow_EmotesOnly"] = "Nur Emotes",
        ["MainWindow_UniqueChat"] = "Einzigartiger Chat (keine wiederholten Nachrichten)",
        ["MainWindow_FollowersOnly"] = "Nur Follower (Mindestalter)",
        ["MainWindow_FollowersOnlyTooltip"] = "Nur Zuschauer, die dem Kanal seit mindestens dieser Anzahl Minuten folgen, können schreiben",
        ["MainWindow_SlowMode"] = "Langsam-Modus (Sek. zwischen Nachrichten)",
        ["MainWindow_SlowModeTooltip"] = "Jeder Benutzer muss diese Anzahl Sekunden zwischen zwei Nachrichten warten",
        ["MainWindow_SaveChatSettings"] = "Chat-Einstellungen speichern",
        ["MainWindow_RefreshChatSettingsTooltip"] = "Einstellungen aktualisieren",
        ["MainWindow_ChatSettingsHeader"] = "CHAT-EINSTELLUNGEN",
        ["MainWindow_ConnectedChatters"] = "VERBUNDENE CHATTER",
        ["MainWindow_UnbanUserHeader"] = "BENUTZER ENTSPERREN",
        ["MainWindow_Unban"] = "Entsperren",
        ["MainWindow_ActiveSanctions"] = "AKTIVE SANKTIONEN",
        ["MainWindow_RefreshSanctionsTooltip"] = "Sanktionen aktualisieren",
    };
}