namespace TTNOverlay.Services;

internal static partial class RuStrings
{
    private static readonly Dictionary<string, string> ModerationPanelEntries = new()
    {
        ["MainWindow_MuteMenu"] = "🔇 Замутить",
        ["MainWindow_WarnMenu"] = "⚠ Предупредить",
        ["MainWindow_BanMenu"] = "⛔ Забанить",
        ["MainWindow_SettingsTooltip"] = "Настройки",
        ["MainWindow_ToggleBordersTooltip"] = "Показать/скрыть границы",
        ["MainWindow_RefreshWithIcon"] = "🔄 Обновить",
        ["MainWindow_LogoutWithIcon"] = "🚪 Выйти",
        ["MainWindow_MuteDurationHeader"] = "ДЛИТЕЛЬНОСТЬ МУТА",
        ["MainWindow_1Minute"] = "1 минута",
        ["MainWindow_5Minutes"] = "5 минут",
        ["MainWindow_10Minutes"] = "10 минут",
        ["MainWindow_30Minutes"] = "30 минут",
        ["MainWindow_1Hour"] = "1 час",
        ["MainWindow_24Hours"] = "24 часа",
        ["MainWindow_3Days"] = "3 дня",
        ["MainWindow_7Days"] = "7 дней",
        ["MainWindow_14Days"] = "14 дней",
        ["MainWindow_1Day"] = "1 день",
        ["MainWindow_1Week"] = "1 неделя",
        ["MainWindow_1Month"] = "1 месяц",
        ["MainWindow_3Seconds"] = "3 секунды",
        ["MainWindow_5Seconds"] = "5 секунд",
        ["MainWindow_10Seconds"] = "10 секунд",
        ["MainWindow_30Seconds"] = "30 секунд",
        ["MainWindow_60Seconds"] = "60 секунд",
        ["MainWindow_120Seconds"] = "120 секунд",
        ["MainWindow_Custom"] = "Своё...",
        ["MainWindow_CustomHoursTooltip"] = "Часы (макс. 336 = 14 дней)",
        ["MainWindow_HoursUnit"] = "часов",
        ["MainWindow_DaysUnit"] = "дней",
        ["MainWindow_SubscribersOnly"] = "Только для подписчиков",
        ["MainWindow_EmotesOnly"] = "Только эмоции",
        ["MainWindow_UniqueChat"] = "Уникальный чат (без повторяющихся сообщений)",
        ["MainWindow_FollowersOnly"] = "Только для подписчиков (мин. возраст)",
        ["MainWindow_FollowersOnlyTooltip"] = "Только зрители, которые подписаны на канал не менее указанного количества минут, могут писать",
        ["MainWindow_SlowMode"] = "Медленный режим (сек. между сообщениями)",
        ["MainWindow_SlowModeTooltip"] = "Каждый пользователь должен ждать указанное количество секунд между сообщениями",
        ["MainWindow_SaveChatSettings"] = "Сохранить настройки чата",
        ["MainWindow_RefreshChatSettingsTooltip"] = "Обновить настройки",
        ["MainWindow_ChatSettingsHeader"] = "НАСТРОЙКИ ЧАТА",
        ["MainWindow_ConnectedChatters"] = "ПОДКЛЮЧЁННЫЕ УЧАСТНИКИ",
        ["MainWindow_UnbanUserHeader"] = "РАЗБАН ПОЛЬЗОВАТЕЛЯ",
        ["MainWindow_Unban"] = "Разбанить",
        ["MainWindow_ActiveSanctions"] = "АКТИВНЫЕ САНКЦИИ",
        ["MainWindow_RefreshSanctionsTooltip"] = "Обновить санкции",
    };
}