namespace TTNOverlay.Services;

internal static partial class EsStrings
{
    private static readonly Dictionary<string, string> ModerationPanelEntries = new()
    {
        ["MainWindow_MuteMenu"] = "🔇 Mutear",
        ["MainWindow_WarnMenu"] = "⚠ Advertir",
        ["MainWindow_BanMenu"] = "⛔ Banear",
        ["MainWindow_SettingsTooltip"] = "Configuración",
        ["MainWindow_ToggleBordersTooltip"] = "Ocultar/mostrar bordes",
        ["MainWindow_RefreshWithIcon"] = "🔄 Actualizar",
        ["MainWindow_LogoutWithIcon"] = "🚪 Cerrar sesión",
        ["MainWindow_MuteDurationHeader"] = "DURACIÓN DEL MUTE",
        ["MainWindow_1Minute"] = "1 minuto",
        ["MainWindow_5Minutes"] = "5 minutos",
        ["MainWindow_10Minutes"] = "10 minutos",
        ["MainWindow_30Minutes"] = "30 minutos",
        ["MainWindow_1Hour"] = "1 hora",
        ["MainWindow_24Hours"] = "24 horas",
        ["MainWindow_3Days"] = "3 días",
        ["MainWindow_7Days"] = "7 días",
        ["MainWindow_14Days"] = "14 días",
        ["MainWindow_1Day"] = "1 día",
        ["MainWindow_1Week"] = "1 semana",
        ["MainWindow_1Month"] = "1 mes",
        ["MainWindow_3Seconds"] = "3 segundos",
        ["MainWindow_5Seconds"] = "5 segundos",
        ["MainWindow_10Seconds"] = "10 segundos",
        ["MainWindow_30Seconds"] = "30 segundos",
        ["MainWindow_60Seconds"] = "60 segundos",
        ["MainWindow_120Seconds"] = "120 segundos",
        ["MainWindow_Custom"] = "Personalizado...",
        ["MainWindow_CustomHoursTooltip"] = "Horas (máx. 336 = 14 días)",
        ["MainWindow_HoursUnit"] = "horas",
        ["MainWindow_DaysUnit"] = "días",
        ["MainWindow_SubscribersOnly"] = "Solo suscriptores",
        ["MainWindow_EmotesOnly"] = "Solo emotes",
        ["MainWindow_UniqueChat"] = "Chat único (sin mensajes repetidos)",
        ["MainWindow_FollowersOnly"] = "Solo seguidores (min. de antigüedad)",
        ["MainWindow_FollowersOnlyTooltip"] = "Solo pueden chatear quienes siguen el canal desde hace al menos esta cantidad de minutos",
        ["MainWindow_SlowMode"] = "Modo lento (seg. entre mensajes)",
        ["MainWindow_SlowModeTooltip"] = "Cada usuario debe esperar esta cantidad de segundos entre un mensaje y el siguiente",
        ["MainWindow_SaveChatSettings"] = "Guardar ajustes del chat",
        ["MainWindow_RefreshChatSettingsTooltip"] = "Actualizar ajustes",
        ["MainWindow_ChatSettingsHeader"] = "AJUSTES DEL CHAT",
        ["MainWindow_ConnectedChatters"] = "CHATTERS CONECTADOS",
        ["MainWindow_UnbanUserHeader"] = "DESBANEAR USUARIO",
        ["MainWindow_Unban"] = "Desbanear",
        ["MainWindow_ActiveSanctions"] = "SANCIONADOS ACTIVOS",
        ["MainWindow_RefreshSanctionsTooltip"] = "Actualizar sancionados",
    };
}
