namespace TTNOverlay.Services;

internal static partial class EnStrings
{
    private static readonly Dictionary<string, string> ModerationPanelEntries = new()
    {
        ["MainWindow_MuteMenu"] = "🔇 Mute",
        ["MainWindow_WarnMenu"] = "⚠ Warn",
        ["MainWindow_BanMenu"] = "⛔ Ban",
        ["MainWindow_SettingsTooltip"] = "Settings",
        ["MainWindow_ToggleBordersTooltip"] = "Show/hide borders",
        ["MainWindow_RefreshWithIcon"] = "🔄 Refresh",
        ["MainWindow_LogoutWithIcon"] = "🚪 Log out",
        ["MainWindow_MuteDurationHeader"] = "MUTE DURATION",
        ["MainWindow_1Minute"] = "1 minute",
        ["MainWindow_5Minutes"] = "5 minutes",
        ["MainWindow_10Minutes"] = "10 minutes",
        ["MainWindow_30Minutes"] = "30 minutes",
        ["MainWindow_1Hour"] = "1 hour",
        ["MainWindow_24Hours"] = "24 hours",
        ["MainWindow_3Days"] = "3 days",
        ["MainWindow_7Days"] = "7 days",
        ["MainWindow_14Days"] = "14 days",
        ["MainWindow_1Day"] = "1 day",
        ["MainWindow_1Week"] = "1 week",
        ["MainWindow_1Month"] = "1 month",
        ["MainWindow_3Seconds"] = "3 seconds",
        ["MainWindow_5Seconds"] = "5 seconds",
        ["MainWindow_10Seconds"] = "10 seconds",
        ["MainWindow_30Seconds"] = "30 seconds",
        ["MainWindow_60Seconds"] = "60 seconds",
        ["MainWindow_120Seconds"] = "120 seconds",
        ["MainWindow_Custom"] = "Custom...",
        ["MainWindow_CustomHoursTooltip"] = "Hours (max. 336 = 14 days)",
        ["MainWindow_HoursUnit"] = "hours",
        ["MainWindow_DaysUnit"] = "days",
        ["MainWindow_SubscribersOnly"] = "Subscribers only",
        ["MainWindow_EmotesOnly"] = "Emotes only",
        ["MainWindow_UniqueChat"] = "Unique chat (no repeated messages)",
        ["MainWindow_FollowersOnly"] = "Followers only (min. age)",
        ["MainWindow_FollowersOnlyTooltip"] = "Only viewers who have followed the channel for at least this many minutes can chat",
        ["MainWindow_SlowMode"] = "Slow mode (sec. between messages)",
        ["MainWindow_SlowModeTooltip"] = "Each user must wait this many seconds between one message and the next",
        ["MainWindow_SaveChatSettings"] = "Save chat settings",
        ["MainWindow_RefreshChatSettingsTooltip"] = "Refresh settings",
        ["MainWindow_ChatSettingsHeader"] = "CHAT SETTINGS",
        ["MainWindow_ConnectedChatters"] = "CONNECTED CHATTERS",
        ["MainWindow_UnbanUserHeader"] = "UNBAN USER",
        ["MainWindow_Unban"] = "Unban",
        ["MainWindow_ActiveSanctions"] = "ACTIVE SANCTIONS",
        ["MainWindow_RefreshSanctionsTooltip"] = "Refresh sanctions",
    };
}
